= Parameters

The parent key for all of the following parameters is `grafana_helm`.

== `namespace`

[horizontal]
type:: string
default:: `syn-grafana`

The namespace in which to deploy this component.

== `createNamespace`

[horizontal]
type:: boolean
default:: `true`

Whether to create the namespace specified in `namespace`.

== `namespaceLabels`

[horizontal]
type:: object
default:: `{}`

Additional labels to add to the namespace specified in `namespace`.

== `namespaceAnnotations`

[horizontal]
type:: object
default:: `{}`

Additional annotations to add to the namespace specified in `namespace`.

== `dashboards`

[horizontal]
type:: object
default:: `{}`

An object with dashboards to provision.

== `datasources`

[horizontal]
type:: object
default:: `{}`

An object with datasources to provision.

== `extraConfigMap`

[horizontal]
type:: object
default:: `{}`

An object with extra ConfgiMaps to be deployed

== Example

[source,yaml]
----
namespace: example-namespace
dashboards:
  dashboard-crossplane: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      [...]
datasources:
    'datasource.yaml': |-
        apiVersion: 1
        datasources:
        - name: Prometheus
            type: prometheus
            url: http://prometheus-svc
            access: proxy
            isDefault: true
extraConfigMap:
  'nginx.conf': "# My NGINX config File"
----
